version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
  webserver:
    image: nginx
    restart: unless-stopped
    tty: true
    ports:
      - '80:80'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./:/var/www
      - ./nginx/log/:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge